use_frameworks!

platform :ios, '8.0'

target 'libDrawboard_Example' do
  pod 'libDrawboard', :path => '../'

  pod 'libPhotoPicker', :git => 'https://gitlab.com/luo-wei/libphotopicker.git', :branch => 'master'

  # target 'libDrawboard_Tests' do
  #   inherit! :search_paths
  #
  # end

end
