use_frameworks!

platform :ios, '8.0'

target 'LWDrawboard_Example' do
  pod 'LWDrawboard', :path => '../'

  # pod 'libPhotoPicker', :git => 'https://gitlab.com/ioslibraries1/libphotopicker.git', :branch => 'master'
  # pod 'libColorPicker', :git => 'https://gitlab.com/ioslibraries1/libcolorpicker.git', :branch => 'master'
  pod 'libPhotoPicker', :path => '../../libPhotoPicker', :branch => 'master'
  pod 'libColorPicker', :path => '../../libColorPicker', :branch => 'master'

  pod 'Masonry'
  pod 'MBProgressHUD'

  # target 'LWDrawboard_Tests' do
  #   inherit! :search_paths
  #
  # end

end
