# use_frameworks!

platform :ios, '8.0'

target 'LWDrawboard_Example' do
  pod 'LWDrawboard', :path => '../'

  # pod 'LWPhotoPicker', :git => 'https://gitlab.com/ioslibraries1/libphotopicker.git', :branch => 'master'
  # pod 'LWColorPicker', :git => 'https://gitlab.com/ioslibraries1/libcolorpicker.git', :branch => 'master'
  # pod 'LWPhotoPicker', :path => '../../LWPhotoPicker', :branch => 'master'
  # pod 'LWColorPicker', :path => '../../LWColorPicker', :branch => 'master'

  pod 'LWPhotoPicker',:source => 'https://gitee.com/lw_ios_project/mylibrepo.git'
  pod 'LWColorPicker',:source => 'https://gitee.com/lw_ios_project/mylibrepo.git'

  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'SDWebImage'

  # target 'LWDrawboard_Tests' do
  #   inherit! :search_paths
  #
  # end

end
